#%RAML 1.0 DataType

type: object
properties:
  productId:
    type: number
    required: false
  name:
    type: string
    required: false
  price:
    type: number
    required: false
  quantity:
    type: integer
    required: false