#%RAML 1.0 DataType

type: object
properties:
  purchaseInfoId:
    type: number
    required: false
  employeeId:
    type: integer
    required: true  
  customerId:
    type: integer
    required: true
  cost:
    type: number
    required: false
  amount:
    type: number
    required: false
  date:      
    type: date-only
    required: false