responses:
  200:
    description: PurchaseInfo has been modified successfully
    body:
      application/json:
        type: purchaseInfo
        example: !include api/examples/purchaseInfo-example.json