responses:
  400:
    body:
      application/json:
        type: errorcode-400
  403:
    body:
      application/json:
        type: errorcode-403
  501:
    body:
      application/json:
        type: errorcode-501 