responses:
  204:
  400:
    body:
      application/json:
        type: errorcode-400
  404:
    body:
      application/json:
        type: errorcode-404
  405:
    body:
      application/json:
        type: errorcode-405
  406:
    body:
      application/json:
        type: errorcode-406 