#%RAML 1.0 Library

resourceTypes:    
  collection-item:
    get:
      description: This is used to fetch <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        304:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-304-example.json    
        404:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-404-example.json       
    delete:
      description: This is used to delete <<resourcePathName>>
      responses:
        204:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-204-example.json 
        400:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-400-example.json 
        404:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-404-example.json 
        405:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-405-example.json
        406:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-406-example.json 
    put:
      description: This is used to update <<resourcePathName>>
      body:
        application/json:
          type: <<typeReference>>
          example: <<exampleReference>>
      responses:
        200:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        304:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-304-example.json      
        400:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-400-example.json 
        404:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-404-example.json     