#%RAML 1.0 Library

resourceTypes:
  collection:
    get?:
      description: This is used to fetch <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        304:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-304-reference-example>>  
        400:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-400-reference-example>>      
        404:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-404-reference-example>>      
        500:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-500-reference-example>>
    post?:
      description: This is uset to create <<resourcePathName>>
      body:
        application/json:
          type: <<typeReference>>
          example: <<exampleReference>>
      responses:
        201:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        400:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-400-reference-example>>
        403:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-403-reference-example>>
        501:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-501-reference-example>>
    delete?:
      description: This is used to delete <<resourcePathName>>
      responses:
        204:
        400:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-400-reference-example>>
        404:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-404-reference-example>>
        405:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-405-reference-example>>
        406:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-406-reference-example>>
    put?:
      description: This is used to update <<resourcePathName>>
      body:
        application/json:
          type: <<typeReference>>
          example: <<exampleReference>>
      responses:
        200:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        304:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-304-reference-example>>      
        400:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-400-reference-example>>
        404:
          body:
            application/json:
              type: <<errorcode-reference-type>>
              example: <<errorcode-404-reference-example>>                              
                        
                                                