#%RAML 1.0 Library  
      
resourceTypes:
  collection:
    get:
      description: This is used to fetch <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        400:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-400-example.json           
        500:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-500-example.json
    post:
      description: This is uset to create <<resourcePathName>>
      body:
        application/json:
          type: <<typeReference>>
          example: <<exampleReference>>
      responses:
        201:
          body:
            application/json:
              type: <<typeReference>>
              example: <<exampleReference>>
        400:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-400-example.json
        403:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-403-example.json
        501:
          body:
            application/json:
              type: !include ../dataTypes/error-datatype.raml
              example: !include ../examples/errorcode-501-example.json                                                