#%RAML 1.0
title: ShopManagementSystem

version: v1

securitySchemes:
  oauth_2_0: !include api/security/securityScheme.raml

mediaType: 
- application/json

protocols:
  - HTTP

types:
  customer: !include api/data_types/customer_datatype.raml
  employee: !include api/data_types/employee_datatype.raml
  product: !include api/data_types/product_datatype.raml
  purchaseInfo: !include api/data_types/purchaseInfo_datatype.raml
  
  errorcode: !include api/data_types/errorcode_datatype.json 

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server                 
    
/customers:
  description: A collection of customers
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: customer[]
            example: !include api/examples_array/customer_array.json
      400:
        body:
          application/json:
            example: errorcode
  post:
    is: [client-id-required]
    body:
      application/json:
        type: customer
    responses:
      201:
        body:
          application/json:
            type: customer
            example: !include api/examples/customer_example.json
      400:
        body:
          application/json:
            type: errorcode
      403:
        body:
          application/json:
            type: errorcode                            
/customers/{customerId}:
  description: Get a customer by customerId
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: customer
            example: !include api/examples/customer_example.json
      304:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  delete:
    is: [client-id-required]
    responses:
      200: {}
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  put:
    is: [client-id-required]
    description: Update a customer
    body:
      application/json:
        type: customer
        example: !include api/examples/customer_example.json
    responses:
      200:
        description: Customer has been modified successfully
        body:
          application/json:
            type: customer
            example: !include api/examples/customer_example.json
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode 
/employees:
  description: A collection of empoyees
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: employee[]
            example: !include api/examples_array/employee_array.json
      400:
        body:
          application/json:
            example: errorcode
  post:
    is: [client-id-required]
    body:
      application/json:
        type: employee
    responses:
      201:
        body:
          application/json:
            type: employee
            example: !include api/examples/employee_example.json
      400:
        body:
          application/json:
            type: errorcode
      403:
        body:
          application/json:
            type: errorcode                            
/employees/{employeeId}:
  description: Get a customer by employeeId
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: employee
            example: !include api/examples/employee_example.json
      304:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  delete:
    is: [client-id-required]
    responses:
      200: {}
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  put:
    is: [client-id-required]
    description: Update an employee
    body:
      application/json:
        type: employee
        example: !include api/examples/employee_example.json
    responses:
      200:
        description: Employee has been modified successfully
        body:
          application/json:
            type: employee
            example: !include api/examples/employee_example.json
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
/products:
  description: A collection of products
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: product[]
            example: !include api/examples_array/product_array.json
      400:
        body:
          application/json:
            example: errorcode
  post:
    is: [client-id-required]
    body:
      application/json:
        type: product
    responses:
      201:
        body:
          application/json:
            type: product
            example: !include api/examples/product_example.json
      400:
        body:
          application/json:
            type: errorcode
      403:
        body:
          application/json:
            type: errorcode                            
/products/{productId}:
  description: Get a product by productId
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: product
            example: !include api/examples/product_example.json
      304:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  delete:
    is: [client-id-required]
    responses:
      200: {}
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  put:
    is: [client-id-required]
    description: Update an product
    body:
      application/json:
        type: product
        example: !include api/examples/product_example.json
    responses:
      200:
        description: Product has been modified successfully
        body:
          application/json:
            type: product
            example: !include api/examples/product_example.json
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode  
/purchaseInfos:
  description: A collection of purchaseInfos
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: purchaseInfo[]
            example: !include api/examples_array/purchaseInfo_array.json
      400:
        body:
          application/json:
            example: errorcode
  post:
    is: [client-id-required]
    body:
      application/json:
        type: purchaseInfo
    responses:
      201:
        body:
          application/json:
            type: purchaseInfo
            example: !include api/examples/purchaseInfo_example.json
      400:
        body:
          application/json:
            type: errorcode
      403:
        body:
          application/json:
            type: errorcode                            
/purchaseInfos/{purchaseInfoId}:
  description: Get a purchaseInfo by purchaseInfoId
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: purchaseInfo
            example: !include api/examples/purchaseInfo_example.json
      304:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  delete:
    is: [client-id-required]
    responses:
      200: {}
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode
  put:
    is: [client-id-required]
    description: Update a purchaseInfo
    body:
      application/json:
        type: purchaseInfo
        example: !include api/examples/purchaseInfo_example.json
    responses:
      200:
        description: purchaseInfo has been modified successfully
        body:
          application/json:
            type: purchaseInfo
            example: !include api/examples/purchaseInfo_example.json
      400:
        body:
          application/json:
            type: errorcode
      404:
        body:
          application/json:
            type: errorcode                                               
              