#%RAML 1.0
title: ShopManagementSystem

version: v1

mediaType: 
- application/json

protocols:
  - HTTP
  
traits:
  client-id-required: !include ../traits/client-id-required-trait.raml                                                                      

uses:
  Collection: api/resourceType/resource-type-collection.raml
  CollectionItem: api/resourceType/resource-type-collection-item.raml
  
/customers:
  is: [client-id-required]
  type: {Collection.collection: {typeReference: !include api/dataTypes/customer-datatype.raml,
  exampleReference: !include api/examples/customer-example.json}}
 
/customers/{customerId}:
  is: [client-id-required]
  type: {CollectionItem.collection-item: {typeReference: !include api/dataTypes/customer-datatype.raml,
  exampleReference: !include api/examples/customer-example.json}}    
  
/employees:
  is: [client-id-required]
  type: {Collection.collection: {typeReference: !include api/dataTypes/employee-datatype.raml,
  exampleReference: !include api/examples/employee-example.json}} 
  
/employees/{employeeId}:
  is: [client-id-required]
  type: {CollectionItem.collection-item: {typeReference: !include api/dataTypes/employee-datatype.raml,
  exampleReference: !include api/examples/employee-example.json}}                                                                                                                                                                                                                                                                                            

/products:
  is: [client-id-required]
  type: {Collection.collection: {typeReference: !include api/dataTypes/product-datatype.raml,
  exampleReference: !include api/examples/product-example.json}} 
  
/products/{productId}:
  is: [client-id-required]
  type: {CollectionItem.collection-item: {typeReference: !include api/dataTypes/product-datatype.raml,
  exampleReference: !include api/examples/product-example.json}}           

/purchaseInfos:
  is: [client-id-required]
  type: {Collection.collection: {typeReference: !include api/dataTypes/purchaseInfo-datatype.raml,
  exampleReference: !include api/examples/purchaseInfo-example.json}} 

/purchaseInfos/{purchaseInfoId}:
  is: [client-id-required]
  type: {CollectionItem.collection-item: {typeReference: !include api/dataTypes/purchaseInfo-datatype.raml,
  exampleReference: !include api/examples/purchaseInfo-example.json}}                                                                                                      